version: '3'
services:
  localstack: 
    image: localstack/localstack:1.1.0
    container_name: localstack
    ports:
      - 4566:4566
    networks:
      - simple-network

networks:
  simple-network:
    driver: bridge
    name: simple-network