AWSTemplateFormatVersion: "2010-09-09"
Description: "Monitory Cloud Formation Template"

Mappings:
  Environment:
    global:
      SQSQueueName: btg-monitory
      SQSDLQQueueName: btg-monitory-dlq

Resources: 
  BtgMonitoryQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: 
        Fn::FindInMap:  
          - "Environment"
          - "global"
          - "SQSQueueName"
      DelaySeconds: 0
      MessageRetentionPeriod: 7
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "BtgMonitoryDLQQueue"
            - "Arn"
        maxReceiveCount: 5

  BtgMonitoryDLQQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: 
        Fn::FindInMap: 
          - "Environment"
          - "global"
          - "SQSDLQQueueName"
      DelaySeconds: 0
      MessageRetentionPeriod: 7
            

    
  
